server:
  port: 8080
javax:
  sql:
    DataSource:
      distribuida:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/db-postgres
          user: docker
          password: docker